### ISSUE TITLE
Moving from sqlite to postgres

### ISSUE THREAD

**Issue by malywladek** [nencki-lobi/lobi-www#1]
Traceback (most recent call last):
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "home_profile_user_id_key"
DETAIL:  Key (user_id)=(1) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/core/management/commands/loaddata.py", line 114, in loaddata
    self.load_label(fixture_label)
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/core/management/commands/loaddata.py", line 181, in load_label
    obj.save(using=self.using)
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/bkossows/webapps/django/lib/python3.7/Django-2.2.1-py3.7.egg/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: Problem installing fixture '/home/bkossows/webapps/django/lobi/db_300519.json': Could not load home.Profile(pk=1): duplicate key value violates unique constraint "home_profile_user_id_key"
DETAIL:  Key (user_id)=(1) already exists.

**Comment by malywladek** [comment]
I should give a try to mysql. It used to work on the previous machine.

**Comment by malywladek** [comment]
It's difficult to connect with mysql:
django.db.utils.OperationalError: (1045, "Access denied for user 'lobi'@'localhost' (using password: YES)")

**Comment by mslw** [comment]
I don't know what it is, but I have a feeling that it's something minor. Quickly googling for the postgres issue ("duplicate key value violates unique constraint") gave me some suggestions about having to reset (re-generate?) primary keys in postgres (didn't save it, but might be worth following).

Is there a way to test this locally?

**Comment by malywladek** [comment]
Done with following commands:
python3.7 manage.py dumpdata --exclude contenttypes --exclude auth.permission --exclude auth.user --exclude admin.logentry --natural-foreign > db_data.json
python3.7 manage.py dumpdata auth.user > auth_user.json
sqlite -> postgres
python3.7 manage.py looddata auth_user.json
python3.7 manage.py shell -> from home.models import Profile, Profile.objects.all().delete()
python3.7 manage.py looddata db_data.json
